apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: brainupgrade/hello
  newTag: 8d3b3da5b81b8fc9d2db6b3840c2b1e115fbb19a
resources:
- ../base
