apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: brainupgrade/hello
  newTag: 937b42600148cca368c421a32038bfa7208c255f
resources:
- ../base
