namespace: argocd

bases:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.3.1

resources:
- resources/namespace.yaml
- apps/argocd.yaml 
# - apps/prometheus-grafana.yaml
- apps/hello-e2e.yaml
- apps/hello-uat.yaml
- apps/hello-prod.yaml

patchesStrategicMerge:
- overlays/argocd-cm.yaml
- overlays/argocd-repo-server-deploy.yaml
