apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: brainupgrade/hello
  newTag: 86e5f9a2766d9ea0d6e8ca2899e97971c39f373e
resources:
- ../base
