apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: brainupgrade/hello
  newTag: e3d04a31b937de25288839367869d2ee0dac6fd6
resources:
- ../base
