apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: brainupgrade/hello
  newTag: e97263dc703aef38197d994eaf0a5adb11a23001
resources:
- ../base
