apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: brainupgrade/petclinic
  newTag: bd643862aacbf9fc0defc6ef7ec7ed04cb90c1a3
- name: brainupgrade/spring-petclinic
  newTag: a0d1de83494008c4b08b1b279d958a66cfea7272
resources:
- ../base
