apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: brainupgrade/petclinic
  newTag: 73dd4f4b1a7de760ec951e86bf6898438b61009a
- name: brainupgrade/spring-petclinic
  newTag: a0d1de83494008c4b08b1b279d958a66cfea7272
resources:
- ../base
