apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: brainupgrade/spring-petclinic
  newTag: 73dd4f4b1a7de760ec951e86bf6898438b61009a
resources:
- ../base
